# Generated by Django 4.2.26 on 2025-12-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CREDIT', 'Credit card'), ('DEBIT', 'Debit card')], max_length=20),
        ),
    ]
