# Generated by Django 4.2.26 on 2025-11-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for Concert and Sports events. Leave blank for Conferences and Exhibitions.', max_digits=10, null=True),
        ),
    ]
