# Generated by Django 4.2.26 on 2025-11-27 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional link to a login account for this organizer.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
