# Generated by Django 4.2.26 on 2025-11-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_organizer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed description of the event.', null=True),
        ),
    ]
