# Generated by Django 4.2.26 on 2025-12-11 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_organizer_created_at_organizer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('EXHIBITION', 'Exhibition'), ('CONFERENCE', 'Conference'), ('CONCERT', 'Concert'), ('SPORTS', 'Sports Game')], default='EXHIBITION', help_text='Determines whether the event is free/paid and how bookings work.', max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Required for conferences and paid events. Ignored for exhibitions.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for Concert and Sports events. Must be zero or blank for Conferences and Exhibitions.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50000)]),
        ),
    ]
