# Generated by Django 4.2.26 on 2025-11-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingaiaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='pendingaiaction',
            name='description',
        ),
        migrations.AlterField(
            model_name='pendingaiaction',
            name='action_type',
            field=models.CharField(choices=[('create_event', 'Create event'), ('update_event', 'Update event'), ('delete_event', 'Delete event'), ('create_venue', 'Create venue'), ('cancel_booking', 'Cancel booking')], max_length=40),
        ),
    ]
